package apiscan

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/yourusername/apiscan/internal/models"
)

// newReportCmd builds the `apiscan report` command.
// This lets developers quickly view past scan results without re-scanning.
func newReportCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "report [latest|<scan-id>|list]",
		Short: "View or list scan reports",
		Long: `View, list, or export scan reports generated by previous scans.

Examples:
  # View the most recent scan report (summary)
  apiscan report latest

  # List all reports in the output directory
  apiscan report list

  # Show full details for a specific report
  apiscan report latest --full`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			subcommand := "latest"
			if len(args) > 0 {
				subcommand = args[0]
			}
			full, _ := cmd.Flags().GetBool("full")
			outputDir, _ := cmd.Flags().GetString("output-dir")
			return runReport(subcommand, outputDir, full)
		},
	}

	cmd.Flags().Bool("full", false, "show full finding details")
	cmd.Flags().String("output-dir", "./reports", "directory containing scan reports")

	return cmd
}

func runReport(subcommand, outputDir string, full bool) error {
	switch subcommand {
	case "list":
		return listReports(outputDir)
	case "latest":
		return showLatestReport(outputDir, full)
	default:
		return showReportByID(outputDir, subcommand, full)
	}
}

func listReports(outputDir string) error {
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		return fmt.Errorf("reading reports directory %s: %w\n"+
			"Run a scan first: apiscan scan <target> --i-have-authorization", outputDir, err)
	}

	var reports []os.DirEntry
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") && e.Name() != "latest.json" {
			reports = append(reports, e)
		}
	}

	if len(reports) == 0 {
		fmt.Println("No scan reports found. Run a scan first:")
		fmt.Println("  apiscan scan https://api.example.com --i-have-authorization")
		return nil
	}

	// Sort newest first
	sort.Slice(reports, func(i, j int) bool {
		iInfo, _ := reports[i].Info()
		jInfo, _ := reports[j].Info()
		return iInfo.ModTime().After(jInfo.ModTime())
	})

	fmt.Printf("%-50s  %-20s  %s\n", "Report File", "Modified", "Size")
	fmt.Println(strings.Repeat("─", 85))
	for _, r := range reports {
		info, _ := r.Info()
		fmt.Printf("%-50s  %-20s  %d KB\n",
			r.Name(),
			info.ModTime().Format("2006-01-02 15:04:05"),
			info.Size()/1024,
		)
	}
	fmt.Printf("\n%d report(s) found in %s\n", len(reports), outputDir)
	return nil
}

func showLatestReport(outputDir string, full bool) error {
	// Try the symlink first
	latestPath := filepath.Join(outputDir, "latest.json")
	if _, err := os.Stat(latestPath); err != nil {
		// Symlink doesn't exist — find the newest JSON file
		entries, err := os.ReadDir(outputDir)
		if err != nil {
			return fmt.Errorf("no reports found in %s — run a scan first", outputDir)
		}

		var newest string
		var newestTime time.Time
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".json") && e.Name() != "latest.json" {
				info, _ := e.Info()
				if info.ModTime().After(newestTime) {
					newestTime = info.ModTime()
					newest = filepath.Join(outputDir, e.Name())
				}
			}
		}

		if newest == "" {
			return fmt.Errorf("no reports found in %s — run a scan first", outputDir)
		}
		latestPath = newest
	}

	return displayReport(latestPath, full)
}

func showReportByID(outputDir, id string, full bool) error {
	// Try exact filename first
	exactPath := filepath.Join(outputDir, id)
	if _, err := os.Stat(exactPath); err == nil {
		return displayReport(exactPath, full)
	}

	// Search for a report containing the ID
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		return fmt.Errorf("reading reports directory: %w", err)
	}

	for _, e := range entries {
		if strings.Contains(e.Name(), id) {
			return displayReport(filepath.Join(outputDir, e.Name()), full)
		}
	}

	return fmt.Errorf("no report found matching: %s", id)
}

func displayReport(path string, full bool) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading report %s: %w", path, err)
	}

	var result models.ScanResult
	if err := json.Unmarshal(data, &result); err != nil {
		return fmt.Errorf("parsing report: %w", err)
	}

	// Print report header
	fmt.Println()
	fmt.Println("┌─────────────────────────────────────────────────────────────┐")
	fmt.Println("│                  APISCAN REPORT VIEWER                      │")
	fmt.Println("├─────────────────────────────────────────────────────────────┤")
	fmt.Printf("│  Scan ID:   %-48s│\n", truncate(result.ID, 48))
	fmt.Printf("│  Target:    %-48s│\n", truncate(result.Target, 48))
	fmt.Printf("│  Scanned:   %-48s│\n", result.StartedAt.Format("2006-01-02 15:04:05 UTC"))
	fmt.Printf("│  Duration:  %-48s│\n", result.Duration)
	fmt.Printf("│  Status:    %-48s│\n", string(result.Status))
	fmt.Printf("│  Version:   %-48s│\n", result.ScannerVersion)
	fmt.Println("├─────────────────────────────────────────────────────────────┤")
	fmt.Printf("│  🔴 Critical:  %-46d│\n", result.Summary.Critical)
	fmt.Printf("│  🟠 High:      %-46d│\n", result.Summary.High)
	fmt.Printf("│  🟡 Medium:    %-46d│\n", result.Summary.Medium)
	fmt.Printf("│  🔵 Low:       %-46d│\n", result.Summary.Low)
	fmt.Printf("│  ⚪ Info:      %-46d│\n", result.Summary.Informational)
	fmt.Printf("│  Total:        %-46d│\n", result.Summary.TotalFindings)
	fmt.Println("└─────────────────────────────────────────────────────────────┘")

	if len(result.Findings) == 0 {
		fmt.Println("\n✅ No findings in this report.")
		return nil
	}

	// Sort findings: Critical → High → Medium → Low → Info
	sort.Slice(result.Findings, func(i, j int) bool {
		return result.Findings[i].Severity.Score() > result.Findings[j].Severity.Score()
	})

	fmt.Printf("\n  Found %d security issue(s):\n\n", len(result.Findings))

	for i, f := range result.Findings {
		icon := severityIcon(f.Severity)
		fmt.Printf("  %d. %s [%s] %s\n", i+1, icon, f.Severity, f.Title)
		fmt.Printf("     Endpoint:  %s %s\n", f.Endpoint.Method, f.Endpoint.URL)
		fmt.Printf("     OWASP:     %s — %s\n", f.OWASPCategory.ID, f.OWASPCategory.Name)
		fmt.Printf("     CVSS:      %.1f\n", f.CVSSScore)

		if full {
			fmt.Printf("     \n     Description:\n")
			// Word-wrap description at 70 chars
			for _, line := range wrapText(f.Description, 70) {
				fmt.Printf("       %s\n", line)
			}
			fmt.Printf("     \n     Recommendation:\n")
			for _, line := range strings.Split(f.Recommendation, "\n") {
				fmt.Printf("       %s\n", line)
			}
			if f.Evidence.MatchedPattern != "" {
				fmt.Printf("     \n     Evidence: %s\n", f.Evidence.MatchedPattern)
			}
		}
		fmt.Println()
	}

	if !full && len(result.Findings) > 0 {
		fmt.Println("  Tip: use --full to see descriptions and recommendations")
	}

	fmt.Printf("\n  Report file: %s\n\n", path)
	return nil
}

func severityIcon(s models.Severity) string {
	switch s {
	case models.SeverityCritical:
		return "🔴"
	case models.SeverityHigh:
		return "🟠"
	case models.SeverityMedium:
		return "🟡"
	case models.SeverityLow:
		return "🔵"
	default:
		return "⚪"
	}
}

func wrapText(text string, width int) []string {
	words := strings.Fields(text)
	var lines []string
	current := ""

	for _, word := range words {
		if len(current)+len(word)+1 > width && current != "" {
			lines = append(lines, current)
			current = word
		} else {
			if current != "" {
				current += " "
			}
			current += word
		}
	}
	if current != "" {
		lines = append(lines, current)
	}
	return lines
}

// newVersionCmd builds the `apiscan version` command.
func newVersionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print the APIScan version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("APIScan version %s\n", Version)
			fmt.Printf("OWASP API Security Top 10: 2023 Edition\n")
			fmt.Printf("Built with Go — github.com/yourusername/apiscan\n")
		},
	}
}
